package dev.nycode.omsilauncher.localization

data class Strings(
    val ok: String,
    val `continue`: String,
    val instances: String,
    val addNewInstance: String,
    val eCitaro: String = "eCitaro",
    val runInstance: String,
    val launch: String,
    val runEditor: String,
    val launchEditor: String,
    val instancePatchVersion: String,
    val edit: String,
    val delete: String,
    val deleteConfirmation: String,
    val yes: String,
    val no: String,
    val confirmDeletion: (instance: String) -> String,
    val instanceName: String,
    val activateInstance: String,
    val activate: String,
    val closeSteamInfo: String,
    val closeSteam: String,
    val unableToCloseSteam: String,
    val unableToCloseSteamTitle: String,
    val createBaseGame: String,
    val baseGameExplanation: String,
    val setup: String,
    val setupChooseDirectory: String,
    val setupChooseDirectoryWarning: String,
    val chooseGameFileDirectory: String,
    val noGameFileDirectory: String,
    val newInstance: String,
    val biArticulatedBusPatch: String,
    val tramPatch: String,
    val createANewInstance: String,
    val instanceDirectory: String,
    val patchVersion: String,
    val use4gbPatch: String,
    val createInstance: String,
    val continueSetup: String,
    val setupLauncherDirectoryHeadline: String,
    val setupOmsiDirectoryHeadline: String,
    val setupStepCopyGameFiles: String,
    val setupStepCopyManifest: String,
    val setupStepSavingConfiguration: String,
    val setupStepCreatingInstancesJson: String,
    val startInstance: String,
    val startEditorInstance: String,
    val selectedPatchVersion: (patchVersion: String) -> String,
    val editInstance: String,
    val deleteInstance: String,
)
